/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.98
 * Generated at: 2025-02-15 06:13:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/all_component/allCss.jsp", Long.valueOf(1738596331000L));
    _jspx_dependants.put("/all_component/navbar.jsp", Long.valueOf(1739597534000L));
    _jspx_dependants.put("/all_component/footer.jsp", Long.valueOf(1739598146000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Ebook: Index</title>\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write(" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\"\n");
      out.write("  integrity=\"sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N\"\n");
      out.write(" crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write(" <script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js\" \n");
      out.write(" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" \n");
      out.write(" crossorigin=\"anonymous\">\n");
      out.write(" </script>\n");
      out.write(" \n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"\n");
      out.write(" integrity=\"sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN\"\n");
      out.write("  crossorigin=\"anonymous\">\n");
      out.write("  </script>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js\"\n");
      out.write(" integrity=\"sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+\"\n");
      out.write("  crossorigin=\"anonymous\">\n");
      out.write("  </script>\n");
      out.write("  \n");
      out.write("  <link rel=\"stylesheet\"\n");
      out.write("   href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css\" integrity=\"sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==\" \n");
      out.write("  crossorigin=\"anonymous\"\n");
      out.write("   referrerpolicy=\"no-referrer\" />\n");
      out.write("   \n");
      out.write("   <link rel=\"stylesheet\" href=\"all_component/style.css\">");
      out.write("\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write(".back-img {\n");
      out.write("  background: url(\"img/book1.jpg\");\n");
      out.write("  min-height: 60vh; \n");
      out.write("  width: 100%; \n");
      out.write("  background-size: cover; \n");
      out.write("  background-repeat: no-repeat;\n");
      out.write("  background-position: bottom; \n");
      out.write("}\n");
      out.write("\n");
      out.write(".crd-ho:hover {\n");
      out.write("  background-color: #fcf7f7;\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body style=\"background-color: #f7f7f7\">\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Ebook Shop</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\n");
      out.write("    <style>\n");
      out.write("        .bg-custom {\n");
      out.write("            background-color: #01579b;\n");
      out.write("        }\n");
      out.write("        .navbar-dark .navbar-nav .nav-link {\n");
      out.write("            color: white;\n");
      out.write("            font-weight: 500;\n");
      out.write("        }\n");
      out.write("        .navbar-dark .navbar-nav .nav-link:hover {\n");
      out.write("            color: #01579b;\n");
      out.write("        }\n");
      out.write("        .header-bar {\n");
      out.write("            height: 10px;\n");
      out.write("            background-color: #01579b;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"container-fluid\"\n");
      out.write("style=\"height:10px; background-color:#01579b\"\n");
      out.write(">\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("    <div class=\"header-bar\"></div>\n");
      out.write("    \n");
      out.write("    <div class=\"container-fluid p-3 bg-light \">\n");
      out.write("        <div class=\"row \">\n");
      out.write("            <div class=\"col-md-3 text-success\">\n");
      out.write("                <h3 class=\"text-primary mb-0\">\n");
      out.write("                    <i class=\"fa-solid fa-book\"></i> Ebooks\n");
      out.write("                </h3>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-6\">\n");
      out.write("                <form class=\"form-inline\">\n");
      out.write("                    <input class=\"form-control mr-2\" type=\"search\" placeholder=\"Search for books...\" aria-label=\"Search\">\n");
      out.write("                    <button class=\"btn btn-primary\" type=\"submit\">Search</button>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-3 text-right\">\n");
      out.write("                <a href=\"login.jsp\" class=\"btn btn-success\">Login</a>\n");
      out.write("                <a href=\"register.jsp\" class=\"btn btn-primary text-white\">Register</a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-dark bg-custom\">\n");
      out.write("        <a class=\"navbar-brand\" href=\"#\"><i class=\"fa-solid fa-house\"></i></a>\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\">\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("        </button>\n");
      out.write("\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("            <ul class=\"navbar-nav ml-auto\">\n");
      out.write("               <!--  <li class=\"nav-item active\"><a class=\"nav-link\" href=\"#\"><i class=\"fa-solid fa-house\"></i>Home</a></li> -->\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"#\"><i class=\"fa-solid fa-book-open\"></i>Recent Books</a></li>\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link\" href=\"#\"><i class=\"fa-solid fa-book-open\"></i>New Books</a></li>\n");
      out.write("                <li class=\"nav-item\"><a class=\"nav-link \" href=\"#\"><i class=\"fa-solid fa-book-open\"></i>Old Books</a></li>\n");
      out.write("            </ul>\n");
      out.write("            <form class=\"form-inline my-2 my-lg-0\">\n");
      out.write("                <button class=\"btn btn-light my-2 my-sm-0\" type=\"submit\">\n");
      out.write("                <i class=\"fa-solid fa-gears\"></i>Settings\n");
      out.write("                </button>\n");
      out.write("                <button class=\"btn btn-light my-2 my-sm-0 ml-1\" type=\"submit\">\n");
      out.write("                <i class=\"fa-solid fa-square-phone\"></i>Contact Us</button>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"></script>\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js\"></script>\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("<div class=\"container-fluid back-img\">\n");
      out.write("<h2 class=\"text-center text-white \">EBook shop</h2>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!--Recent Book Section  -->\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"container mt-2\">\n");
      out.write("  <h3 class=\"text-center\">Recent Viewed Book</h3>\n");
      out.write("  <div class=\"row\">\n");
      out.write("    \n");
      out.write("    <!-- Book Card Start -->\n");
      out.write("    <div class=\"col-md-3\">\n");
      out.write("      <div class=\"card crd-ho\">\n");
      out.write("        <div class=\"card-body text-center\">\n");
      out.write("          <img alt=\"\" src=\"book/java.jpeg\" style=\"width: 150px; height: 200px\" class=\"img-thumbnail\">\n");
      out.write("          <p class=\"mb-1\">Java Programming</p>\n");
      out.write("          <p class=\"text-muted small\">David Cuartielles</p>\n");
      out.write("          <p class=\"text-muted small\">Categories: New</p>\n");
      out.write("\n");
      out.write("          <!-- Buttons inside a flex container -->\n");
      out.write("          <div class=\"d-flex justify-content-center flex-wrap\">\n");
      out.write("            <a href=\"#\" class=\"btn btn-danger btn-sm mx-1\"><i class=\"fa-solid fa-cart-shopping\"></i> Add</a>\n");
      out.write("            <a href=\"#\" class=\"btn btn-success btn-sm mx-1\">View</a>\n");
      out.write("            <a href=\"#\" class=\"btn btn-dark btn-sm mx-1\">299</a>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- Book Card End -->\n");
      out.write("\n");
      out.write("    <!-- Repeat for other books -->\n");
      out.write("    <div class=\"col-md-3\">\n");
      out.write("      <div class=\"card crd-ho\">\n");
      out.write("        <div class=\"card-body text-center\">\n");
      out.write("          <img alt=\"\" src=\"book/java.jpeg\" style=\"width: 150px; height: 200px\" class=\"img-thumbnail\">\n");
      out.write("          <p class=\"mb-1\">Java Programming</p>\n");
      out.write("          <p class=\"text-muted small\">David Cuartielles</p>\n");
      out.write("          <p class=\"text-muted small\">Categories: New</p>\n");
      out.write("\n");
      out.write("          <div class=\"d-flex justify-content-center flex-wrap\">\n");
      out.write("            <a href=\"#\" class=\"btn btn-danger btn-sm mx-1\"><i class=\"fa-solid fa-cart-shopping\"></i> Add</a>\n");
      out.write("            <a href=\"#\" class=\"btn btn-success btn-sm mx-1\">View</a>\n");
      out.write("            <a href=\"#\" class=\"btn btn-dark btn-sm mx-1\">299</a>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"col-md-3\">\n");
      out.write("      <div class=\"card crd-ho\">\n");
      out.write("        <div class=\"card-body text-center\">\n");
      out.write("          <img alt=\"\" src=\"book/java.jpeg\" style=\"width: 150px; height: 200px\" class=\"img-thumbnail\">\n");
      out.write("          <p class=\"mb-1\">Java Programming</p>\n");
      out.write("          <p class=\"text-muted small\">David Cuartielles</p>\n");
      out.write("          <p class=\"text-muted small\">Categories: New</p>\n");
      out.write("\n");
      out.write("          <div class=\"d-flex justify-content-center flex-wrap\">\n");
      out.write("            <a href=\"#\" class=\"btn btn-danger btn-sm mx-1\"><i class=\"fa-solid fa-cart-shopping\"></i> Add</a>\n");
      out.write("            <a href=\"#\" class=\"btn btn-success btn-sm mx-1\">View</a>\n");
      out.write("            <a href=\"#\" class=\"btn btn-dark btn-sm mx-1\">299</a>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"col-md-3\">\n");
      out.write("      <div class=\"card crd-ho\">\n");
      out.write("        <div class=\"card-body text-center\">\n");
      out.write("          <img alt=\"\" src=\"book/java.jpeg\" style=\"width: 150px; height: 200px\" class=\"img-thumbnail\">\n");
      out.write("          <p class=\"mb-1\">Java Programming</p>\n");
      out.write("          <p class=\"text-muted small\">David Cuartielles</p>\n");
      out.write("          <p class=\"text-muted small\">Categories: New</p>\n");
      out.write("\n");
      out.write("          <div class=\"d-flex justify-content-center flex-wrap\">\n");
      out.write("            <a href=\"#\" class=\"btn btn-danger btn-sm mx-1\"><i class=\"fa-solid fa-cart-shopping\"></i> Add</a>\n");
      out.write("            <a href=\"#\" class=\"btn btn-success btn-sm mx-1\">View</a>\n");
      out.write("            <a href=\"#\" class=\"btn btn-dark btn-sm mx-1\">29</a>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <!-- View all button -->\n");
      out.write("  <div class=\"text-center mt-3\">\n");
      out.write("    <a href=\"#\" class=\"btn btn-danger btn-sm text-white\">View All</a>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<hr>\n");
      out.write("\n");
      out.write("<!--New Book Section  -->\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"container mt-2\">\n");
      out.write("  <h3 class=\"text-center\">New Book</h3>\n");
      out.write("  <div class=\"row\">\n");
      out.write("    \n");
      out.write("    <!-- Book Card Start -->\n");
      out.write("    <div class=\"col-md-3\">\n");
      out.write("      <div class=\"card crd-ho\">\n");
      out.write("        <div class=\"card-body text-center\">\n");
      out.write("          <img alt=\"\" src=\"book/java.jpeg\" style=\"width: 150px; height: 200px\" class=\"img-thumbnail\">\n");
      out.write("          <p class=\"mb-1\">Java Programming</p>\n");
      out.write("          <p class=\"text-muted small\">David Cuartielles</p>\n");
      out.write("          <p class=\"text-muted small\">Categories: New</p>\n");
      out.write("\n");
      out.write("          <!-- Buttons inside a flex container -->\n");
      out.write("          <div class=\"d-flex justify-content-center flex-wrap\">\n");
      out.write("            <a href=\"#\" class=\"btn btn-danger btn-sm mx-1\"><i class=\"fa-solid fa-cart-shopping\"></i> Add</a>\n");
      out.write("            <a href=\"#\" class=\"btn btn-success btn-sm mx-1\">View</a>\n");
      out.write("            <a href=\"#\" class=\"btn btn-dark btn-sm mx-1\">299</a>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("   \n");
      out.write("    <div class=\"col-md-3\">\n");
      out.write("      <div class=\"card crd-ho\">\n");
      out.write("        <div class=\"card-body text-center\">\n");
      out.write("          <img alt=\"\" src=\"book/java.jpeg\" style=\"width: 150px; height: 200px\" class=\"img-thumbnail\">\n");
      out.write("          <p class=\"mb-1\">Java Programming</p>\n");
      out.write("          <p class=\"text-muted small\">David Cuartielles</p>\n");
      out.write("          <p class=\"text-muted small\">Categories: New</p>\n");
      out.write("\n");
      out.write("          <div class=\"d-flex justify-content-center flex-wrap\">\n");
      out.write("            <a href=\"#\" class=\"btn btn-danger btn-sm mx-1\"><i class=\"fa-solid fa-cart-shopping\"></i> Add</a>\n");
      out.write("            <a href=\"#\" class=\"btn btn-success btn-sm mx-1\">View</a>\n");
      out.write("            <a href=\"#\" class=\"btn btn-dark btn-sm mx-1\">299</a>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"col-md-3\">\n");
      out.write("      <div class=\"card crd-ho\">\n");
      out.write("        <div class=\"card-body text-center\">\n");
      out.write("          <img alt=\"\" src=\"book/java.jpeg\" style=\"width: 150px; height: 200px\" class=\"img-thumbnail\">\n");
      out.write("          <p class=\"mb-1\">Java Programming</p>\n");
      out.write("          <p class=\"text-muted small\">David Cuartielles</p>\n");
      out.write("          <p class=\"text-muted small\">Categories: New</p>\n");
      out.write("\n");
      out.write("          <div class=\"d-flex justify-content-center flex-wrap\">\n");
      out.write("            <a href=\"#\" class=\"btn btn-danger btn-sm mx-1\"><i class=\"fa-solid fa-cart-shopping\"></i> Add</a>\n");
      out.write("            <a href=\"#\" class=\"btn btn-success btn-sm mx-1\">View</a>\n");
      out.write("            <a href=\"#\" class=\"btn btn-dark btn-sm mx-1\">299</a>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"col-md-3\">\n");
      out.write("      <div class=\"card crd-ho\">\n");
      out.write("        <div class=\"card-body text-center\">\n");
      out.write("          <img alt=\"\" src=\"book/java.jpeg\" style=\"width: 150px; height: 200px\" class=\"img-thumbnail\">\n");
      out.write("          <p class=\"mb-1\">Java Programming</p>\n");
      out.write("          <p class=\"text-muted small\">David Cuartielles</p>\n");
      out.write("          <p class=\"text-muted small\">Categories: New</p>\n");
      out.write("\n");
      out.write("          <div class=\"d-flex justify-content-center flex-wrap\">\n");
      out.write("            <a href=\"#\" class=\"btn btn-danger btn-sm mx-1\"><i class=\"fa-solid fa-cart-shopping\"></i> Add</a>\n");
      out.write("            <a href=\"#\" class=\"btn btn-success btn-sm mx-1\">View</a>\n");
      out.write("            <a href=\"#\" class=\"btn btn-dark btn-sm mx-1\">29</a>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <!-- View all button -->\n");
      out.write("  <div class=\"text-center mt-3\">\n");
      out.write("    <a href=\"#\" class=\"btn btn-danger btn-sm text-white\">View All</a>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<hr>\n");
      out.write("\n");
      out.write("<!--Used Book Section  -->\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"container mt-2\" >\n");
      out.write("<h3 class=\"text-center\">Used Book</h3>\n");
      out.write("<div class=\"row\">\n");
      out.write("<div class=\"col-md-3\">\n");
      out.write("<div class=\"card crd-ho\">\n");
      out.write("<div class=\"card-body text-center\">\n");
      out.write("<img alt=\"\" src=\"book/java.jpeg\" style=\"width: 150px;height: 200px\"\n");
      out.write("class=\"img-thumblin\">\n");
      out.write("<p >Java programming</p>\n");
      out.write("<p>David Cuartielles</p>\n");
      out.write("<p> Categories:Used</p>\n");
      out.write("<div class=\"row  \">\n");
      out.write("\n");
      out.write("<a href=\"\" class=\"btn btn-success btn-sm ml-5\">View Details</a>\n");
      out.write("<a href=\"\" class=\"btn btn-dark btn-sm ml-1\">29</a>\n");
      out.write("\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"col-md-3\">\n");
      out.write("<div class=\"card crd-ho\">\n");
      out.write("<div class=\"card-body text-center\">\n");
      out.write("<img alt=\"\" src=\"book/java.jpeg\" style=\"width: 150px;height: 200px\"\n");
      out.write("class=\"img-thumblin\">\n");
      out.write("<p >Java programming</p>\n");
      out.write("<p>David Cuartielles</p>\n");
      out.write("<p> Categories:New</p>\n");
      out.write("<div class=\"row \">\n");
      out.write("<a href=\"\" class=\"btn btn-success btn-sm ml-5\">View Details</a>\n");
      out.write("<a href=\"\" class=\"btn btn-dark btn-sm ml-1\">299</a>\n");
      out.write("\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"col-md-3\">\n");
      out.write("<div class=\"card crd-ho\">\n");
      out.write("<div class=\"card-body text-center\">\n");
      out.write("<img alt=\"\" src=\"book/java.jpeg\" style=\"width: 150px;height: 200px\"\n");
      out.write("class=\"img-thumblin\">\n");
      out.write("<p >Java programming</p>\n");
      out.write("<p>David Cuartielles</p>\n");
      out.write("<p> Categories:New</p>\n");
      out.write("<div class=\"row \">\n");
      out.write("<a href=\"\" class=\"btn btn-success btn-sm ml-5\">View Details</a>\n");
      out.write("<a href=\"\" class=\"btn btn-dark btn-sm ml-1\">299</a>\n");
      out.write("\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"col-md-3\">\n");
      out.write("<div class=\"card crd-ho\">\n");
      out.write("<div class=\"card-body text-center\">\n");
      out.write("<img alt=\"\" src=\"book/java.jpeg\" style=\"width: 150px;height: 200px\"\n");
      out.write("class=\"img-thumblin\">\n");
      out.write("<p >Java programming</p>\n");
      out.write("<p>David Cuartielles</p>\n");
      out.write("<p> Categories:New</p>\n");
      out.write("<div class=\"row \">\n");
      out.write("<a href=\"\" class=\"btn btn-success btn-sm ml-5\">View Details</a>\n");
      out.write("<a href=\"\" class=\"btn btn-dark btn-sm ml-1\">299</a>\n");
      out.write("\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("<!-- View all button -->\n");
      out.write("<div class=\"text-center mt-3\">\n");
      out.write("<a href=\"\" class=\"btn btn-danger btn-sm text-white\">View All</a>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!--Footer Section  -->\n");
      out.write("\n");
      out.write("<div class=\"container-fluid text-center text-white p-3 mt-3\"\n");
      out.write(" style=\"background-color: #01579b;\">\n");
      out.write("\n");
      out.write("<div class=\"container mx-auto px-4 flex flex-col md:flex-row justify-between items-center\">\n");
      out.write("        \n");
      out.write("      <!--  Left Section -->\n");
      out.write("        <div class =\"text-center md:text-left mb-4 md:mb-0\">\n");
      out.write("          <h2 class=\"text-xl font-semibold\">E-Book Shop</h2>\n");
      out.write("          <p class=\"text-sm text-gray-400\">\n");
      out.write("            Discover, read, and collect your favorite books in one place.\n");
      out.write("          </p>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("     <!--   Copyright  -->\n");
      out.write("      <div class=\"text-center text-gray-500 text-sm mt-4\">\n");
      out.write("        &copy; All rights reserved.\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("</div>");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
